### PR TITLE
Improve code style and update dependencies

### PR DESCRIPTION
**Pull request by vaihtovirta**
Hello! 
Firstly thank you for nice component, it helped me to build custom popover for my client 😄 
Just wanted to apply some improvements, please review it. If you have any questions or suggestions, please let me know.

Here is list of changes that introduced by this PR:
- introduce eslint
- apply eslint rules
- bump react, react-dom, react-hot-loader

### CODE REVIEW

**Comment by dphaener** [comment]
@vaihtovirta  👍 Thanks for this! I like where it's heading. This is quite a bit of refactoring. I was very bad about writing tests for this when I created it, but I feel like it would be appropriate with all the changes made. I am going to merge this into a v1.0 branch and write some tests for everything before releasing. PR's on that branch for tests are welcome!

**Comment by dphaener** [comment]
@vaihtovirta Ok so it looks like I can't simply change the target branch for a PR. :/ Can you close this one and open a new one that targets the `1.x` branch?

**Comment by vaihtovirta** [comment]
@dphaener Hope I will be able to add some tests shortly.
I've opened new PR https://github.com/Legitcode/popover/pull/6

**Comment by vaihtovirta** [comment]
Closing in favor of https://github.com/Legitcode/popover/pull/6

**Pull request closed without merging**
